

// FIX: Changed to a namespace import to handle potential module resolution issues.
import * as firebaseApp from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  addDoc, 
  getDocs,
  getDoc,
  doc,
  query, 
  orderBy, 
  serverTimestamp,
  Timestamp
} from 'firebase/firestore';
import { firebaseConfig, isFirebaseConfigured } from '../firebaseConfig';
import type { BlogPost } from '../types';

// Initialize Firebase
const app = isFirebaseConfigured() ? firebaseApp.initializeApp(firebaseConfig) : null;
const db = app ? getFirestore(app) : null;

const postsCollection = db ? collection(db, 'posts') : null;

// Type for creating a post, without fields generated by the server
export type NewBlogPost = Omit<BlogPost, 'id' | 'createdAt'>;

export const getPosts = async (): Promise<BlogPost[]> => {
  if (!postsCollection) {
    console.warn("Firebase is not configured. Returning empty array.");
    return [];
  }
  const q = query(postsCollection, orderBy('createdAt', 'desc'));
  const postsSnapshot = await getDocs(q);
  const postsList = postsSnapshot.docs.map(doc => {
    const data = doc.data();
    return {
      id: doc.id,
      ...data,
      // Convert Firestore Timestamp to ISO string to match existing type
      createdAt: (data.createdAt as Timestamp)?.toDate().toISOString() || new Date().toISOString(),
    } as BlogPost
  });
  return postsList;
};

export const getPost = async (id: string): Promise<BlogPost | null> => {
    if (!db) {
      console.warn("Firebase is not configured. Returning null.");
      return null;
    }
    const postDocRef = doc(db, 'posts', id);
    const postDoc = await getDoc(postDocRef);

    if (postDoc.exists()) {
        const data = postDoc.data();
        return {
            id: postDoc.id,
            ...data,
            createdAt: (data.createdAt as Timestamp)?.toDate().toISOString() || new Date().toISOString(),
        } as BlogPost;
    } else {
        return null;
    }
};

export const addPost = async (post: NewBlogPost): Promise<string> => {
  if (!postsCollection) {
    throw new Error("Firebase is not configured. Cannot add post.");
  }
  const docRef = await addDoc(postsCollection, {
    ...post,
    createdAt: serverTimestamp()
  });
  return docRef.id;
};
